<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>AutocompleteMenuNS</RootNamespace>
    <AssemblyName>AutocompleteMenu</AssemblyName>
    <Description>AutocompleteMenu WinForms control (embedded from Pavel Torgashov's library, LGPLv3)</Description>
  </PropertyGroup>

</Project>
